# Generated by Django 3.2 on 2021-08-14 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(blank=True, default=None, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=120)),
                ('number_of_people', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'book',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=240)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('gallery_name', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),

        migrations.CreateModel(
            name='menu_category',
            fields=[
                ('menu_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_cat_name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
            },
        ),
        migrations.CreateModel(
            name='gift',
            fields=[
                ('gift_id', models.AutoField(primary_key=True, serialize=False)),
                ('gift_name', models.CharField(max_length=120)),
                ('gift_sl_no', models.CharField(blank=True, max_length=120)),
                ('gift_type', models.CharField(choices=[('Voucher', 'Voucher'), ('Product', 'Product')], max_length=150)),
                ('gift_meta', models.CharField(max_length=255)),
                ('gift_description', models.TextField()),
                ('gift_image', models.ImageField(upload_to='gifts/')),
                ('gift_price', models.IntegerField(blank=True, null=True)),
                ('gift_weight', models.IntegerField(blank=True, null=True)),
                ('gift_dimension', models.CharField(blank=True, max_length=150, null=True)),
                ('gift_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lakshabay.category')),
            ],
        ),
        migrations.CreateModel(
            name='Fitem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=120)),
                ('item_description', models.TextField()),
                ('item_price', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(default='defaultfood.jpg', upload_to='Online Food')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lakshabay.menu_category')),
            ],
        ),
    ]
