# Generated by Django 3.2 on 2021-08-17 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Lakshabay', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='Menu/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Lakshabay.menu_category')),
            ],
        ),
    ]
