# Generated by Django 3.2 on 2021-08-16 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default='', max_length=50)),
                ('lastname', models.CharField(blank=True, default='', max_length=50)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=264)),
                ('address2', models.CharField(blank=True, default='', max_length=265)),
                ('city', models.CharField(blank=True, default='', max_length=30)),
                ('state', models.CharField(default='', max_length=30)),
                ('zipcode', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=15)),
                ('aditional_info', models.TextField(blank=True, default='additional information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Billing Addresses',
            },
        ),
    ]
